### ISSUE TITLE
TechnicalNote/README.md 오타 제보

### ISSUE THREAD

**Issue by sojeongw** [jobhope/TechnicalNote#114]
안녕하세요.

github 파트의 [repository를 clone할 때 모든 branch를 loacl에 받기] 에서
`loacl`로 오타가 나있어 제보드립니다.

감사합니다.

**Comment by Stupid07** [comment]
제보해주셔서 감사합니다!
수정 완료하였습니다:+1:

**Comment by tdm1223** [comment]
2020.02.09
