### ISSUE TITLE
[WEB] 웹 사이트의 속도를 개선시키는 방법

### ISSUE THREAD

**Issue by rlatjdwo555** [jobhope/TechnicalNote#26]
프론트와 백엔드를 나눠서 설명

**Comment by Stupid07** [comment]
### 모바일에서 웹 사이트의 속도를 개선 시킬 수있는 AMP
- [AMP와 PWA](https://github.com/jobhope/TechnicalNote/blob/master/AMPandPWA.md)

**Comment by rlatjdwo555** [comment]
https://github.com/jobhope/TechnicalNote/blob/master/web/PageSpeedInsights.md
