### ISSUE TITLE
[네트워크]OSI 7 계층이란?

### ISSUE THREAD

**Issue by Stupid07** [jobhope/TechnicalNote#3]

**Comment by Stupid07** [comment]
- 계층별 표와 링크 달기
- TCP/IP 4계층은 따로 문서를 만들고 링크 달기
- 가독성을 위해 글을 줄일 필요성이 있음

**Comment by Stupid07** [comment]
- 개인 의견을 추가한 부분을 키워드 위주로 요약 추천

**Comment by Stupid07** [comment]
- 계층별 표와 링크 달기 완료
- TCP/IP 글이 완성되면 링크 달 예정
- 가독성을 위한 글 요약은 pass

**Comment by tdm1223** [comment]
아니 왜 아직도 UPDATE죠?
